# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: true
sudo: false


matrix:
  include:
    - os: linux
      r: devel

allow_failures:
    - os: linux
      r: release

    - os: osx
      r: release

    - os: osx
      r: devel

before_deploy:
  # so no overwrite of linux build
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi

r_packages:
- stringr
- rmarkdown
- knitr
- CompQuadForm
- GSA
- KernSmooth
- rmarkdown
- testthat
- rex
- Hmisc
- shiny
- BiocManager

bioc_packages:
- limma
- DESeq2
- edgeR
- GEOquery

r_github_packages:
- hadley/ggplot2
- jimhester/covr

r_build_args: "--html"

r_check_args: "--as-cran --timings"

after_success:
  - Rscript -e 'covr::codecov()'
